{% set version = "1.20.1" %}

package:
  name: grpcio
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/grpcio/grpcio-{{ version }}.tar.gz
  sha256: 84eb47b1a47e206e78f453fb92a155ed0d18d2ca8747f5c67e4b50b9c37180a7
  patches:
    - macos_use_distutils.patch
    - windows_ssl_lib_names.patch             # [win and openssl != "1.1.1"]
    - windows_ssl_lib_names_openssl111.patch  # [win and openssl == "1.1.1"]
    - extra_include_and_lib_dirs.patch        # [win]

build:
  number: 1000
  # protobuf does not support Visual C++ 2008, skip windows py27
  skip: True  # [win and vc<10]

requirements:
  build:
    - {{ compiler('c') }}     # [not win]
    - {{ compiler('cxx') }}   # [not win]
  host:
    - python
    - pip
    - six >=1.5.2
    - futures >=2.2.0   # [py27]
    - enum34 >=1.0.4    # [py27]
    - zlib
    - openssl
    - c-ares            # [unix]
    - m2w64-toolchain   # [win]
    - libpython         # [win]
  run:
    - python
    - setuptools
    - six >=1.5.2
    - futures >=2.2.0   # [py27]
    - enum34 >=1.0.4    # [py27]
    - zlib
    - openssl
    - {{ pin_compatible("c-ares") }}  # [unix]
    - m2w64-gcc-libs   # [win]

test:
  imports:
    - grpc
    - grpc._cython
    - grpc._cython._cygrpc
    - grpc.beta
    - grpc.framework
    - grpc.framework.common
    - grpc.framework.foundation
    - grpc.framework.interfaces
    - grpc.framework.interfaces.base
    - grpc.framework.interfaces.face

about:
  home: https://grpc.io
  license: Apache 2.0
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  license_family: APACHE
  summary: HTTP/2-based RPC framework

extra:
  recipe-maintainers:
    - ocefpaf
    - jcrist
